# Generated by Django 4.2.1 on 2024-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
