# Generated by Django 4.2.1 on 2024-03-16 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_gender_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
