# Generated by Django 4.2.1 on 2024-03-16 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='emergency_contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
