# Generated by Django 4.2.1 on 2024-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccount_birthday_useraccount_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
