# Generated by Django 4.2.1 on 2023-06-09 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('smoke', models.IntegerField(default=0, null=True)),
                ('temperature', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('distance', models.IntegerField()),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create_map.sensor')),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create_map.sign')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('branch_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_sensor', to='create_map.sensor')),
                ('main_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_sensor', to='create_map.sensor')),
            ],
        ),
    ]
