# Generated by Django 4.2.1 on 2023-08-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0004_remove_sensor_is_critical_remove_sensor_is_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='state',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
