# Generated by Django 4.2.1 on 2023-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0005_floor_state_alter_sensor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='battery_state',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='connection_state',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='smoke_state',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='temperature_state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
