# Generated by Django 4.2.1 on 2023-09-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0006_sensor_battery_state_sensor_connection_state_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertMessage',
            new_name='Alert_Message',
        ),
    ]
