# Generated by Django 4.2.1 on 2023-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0007_rename_alertmessage_alert_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_records',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alert_records',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
