# Generated by Django 4.2.1 on 2023-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0008_alter_alert_records_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='rooms',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
