# Generated by Django 4.2.1 on 2023-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0009_floor_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='isMute',
            field=models.BooleanField(null=True),
        ),
    ]
