# Generated by Django 4.2.1 on 2023-10-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0011_remove_sensor_ismute_alerts_ismute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unmute_Alert_Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmute_time', models.DateTimeField(null=True)),
                ('alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create_map.alerts')),
            ],
        ),
    ]
