# Generated by Django 4.2.1 on 2023-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0012_unmute_alert_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='fire_drill_smoke',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='fire_drill_smoke_state',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='fire_drill_temperature',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='fire_drill_temperature_state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
