# Generated by Django 4.2.1 on 2023-12-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0013_sensor_fire_drill_smoke_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, null=True)),
                ('create_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, null=True)),
                ('description', models.TextField(max_length=20, null=True)),
                ('rooms', models.TextField(max_length=30, null=True)),
                ('priority', models.IntegerField(default=0, null=True)),
                ('state', models.IntegerField(default=0, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50, null=True)),
                ('last_name', models.TextField(max_length=50, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('role', models.IntegerField(default=0, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alert_records',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='alert_records',
            name='message',
        ),
        migrations.RemoveField(
            model_name='alert_records',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='message',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_sensor',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='main_sensor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='room',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='room',
        ),
        migrations.RemoveField(
            model_name='unmute_alert_timer',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='wire',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='wire',
            name='sign',
        ),
        migrations.DeleteModel(
            name='Alert_Message',
        ),
        migrations.DeleteModel(
            name='Alert_Records',
        ),
        migrations.DeleteModel(
            name='Alerts',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
        migrations.DeleteModel(
            name='Unmute_Alert_Timer',
        ),
        migrations.DeleteModel(
            name='Wire',
        ),
        migrations.AddField(
            model_name='task',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create_map.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='create_map.user'),
        ),
    ]
