# Generated by Django 4.2.1 on 2024-03-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0016_task_assignee_task_reportor_alter_task_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
    ]
