# Generated by Django 4.2.1 on 2024-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0017_rename_user_comment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
