# Generated by Django 4.2.1 on 2024-03-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0018_task_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
