# Generated by Django 4.2.1 on 2024-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0019_rename_name_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.TextField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
