# Generated by Django 4.2.1 on 2024-03-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0020_project_code_task_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
