# Generated by Django 4.2.1 on 2024-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0024_project_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
