# Generated by Django 4.2.1 on 2024-03-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_map', '0025_alter_project_create_at_alter_project_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
    ]
